### ISSUE TITLE
Grab notification never sending with pushover

### ISSUE THREAD

**Issue by xcrailer** [NiNiyas/Bettarr-Notifications#1]
The Grab function within the script never seems to trigger. The import function works and gives me download notifications but grab notifications never send in either sonarr or radarr. The logs don't show anything.

**Comment by NiNiyas** [comment]
I am gonna need more details. Sonarr and Radarr version? Arr debug logs when the script triggers.

**Comment by xcrailer** [comment]
I am using the Standard version, not the tor. I am trying to figure out the versions, the provider I use custom compiles so they may be a few releases behind.

I see these in the logs

2022-04-21 13:58:30.6|Error|sonarr.py|Traceback (most recent call last):
2022-04-21 13:58:30.6|Error|sonarr.py|  File "/home/(removed)/pushover/sonarr.py", line 733, in <module>
2022-04-21 13:58:30.6|Error|sonarr.py|    grab()
2022-04-21 13:58:30.6|Error|sonarr.py|  File "/home/(removed)/pushover/sonarr.py", line 205, in grab
2022-04-21 13:58:30.6|Error|sonarr.py|    trailer_link = ratings_sonarr.trailer

2022-04-21 13:55:48.9|Error|radarr.py|Traceback (most recent call last):
2022-04-21 13:55:48.9|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 435, in <module>
2022-04-21 13:55:48.9|Error|radarr.py|    grab()
2022-04-21 13:55:48.9|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 224, in grab
2022-04-21 13:55:48.9|Error|radarr.py|    ratings_radarr.ratings, release_group, quality,
2022-04-21 13:55:48.9|Error|radarr.py|AttributeError: module 'addons.ratings_radarr' has no attribute 'ratings'

**Comment by NiNiyas** [comment]
Thanks. I just pushed a possible fix for this. Could you please update the script and test it again?

**Comment by xcrailer** [comment]
The fix you pushed seems to have worked for sonarr but I still get this error in radarr.

2022-04-21 16:18:00.3|Error|radarr.py|Traceback (most recent call last):
2022-04-21 16:18:00.3|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 150, in grab
2022-04-21 16:18:00.3|Error|radarr.py|    for p in tmdbProviders["results"][country_code]['flatrate']:
2022-04-21 16:18:00.3|Error|radarr.py|KeyError: 'US'
2022-04-21 16:18:00.3|Error|radarr.py|During handling of the above exception, another exception occurred:
2022-04-21 16:18:00.3|Error|radarr.py|Traceback (most recent call last):
2022-04-21 16:18:00.3|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 435, in <module>
2022-04-21 16:18:00.3|Error|radarr.py|    grab()
2022-04-21 16:18:00.3|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 156, in grab
2022-04-21 16:18:00.3|Error|radarr.py|    for x in ratings_radarr.mdblist_data['streams']:
2022-04-21 16:18:00.3|Error|radarr.py|AttributeError: module 'addons.ratings_radarr' has no attribute 'mdblist_data'
2022-04-21 16:18:50.4|Error|TaskExtensions|Task Error

**Comment by NiNiyas** [comment]
Pushed another one. Please check and report back. Thanks!

**Comment by xcrailer** [comment]
Seems to be shooting out the same errors.

2022-04-21 16:56:22.8|Error|radarr.py|Traceback (most recent call last):
2022-04-21 16:56:22.8|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 150, in grab
2022-04-21 16:56:22.8|Error|radarr.py|    for p in tmdbProviders["results"][country_code]['flatrate']:
2022-04-21 16:56:22.8|Error|radarr.py|KeyError: 'US'
2022-04-21 16:56:22.8|Error|radarr.py|During handling of the above exception, another exception occurred:
2022-04-21 16:56:22.8|Error|radarr.py|Traceback (most recent call last):
2022-04-21 16:56:22.8|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 433, in <module>
2022-04-21 16:56:22.8|Error|radarr.py|    grab()
2022-04-21 16:56:22.8|Error|radarr.py|  File "/home/(removed)/pushover/radarr.py", line 155, in grab
2022-04-21 16:56:22.8|Error|radarr.py|    for x in ratings_radarr.mdblist_data['streams']:
2022-04-21 16:56:22.8|Error|radarr.py|AttributeError: module 'addons.ratings_radarr' has no attribute 'mdblist_data'

**Comment by NiNiyas** [comment]
Does `Available On` field work on Sonarr and what series are you downloading?

**Comment by xcrailer** [comment]
This is what Sonarr is outputting to pushover. https://i.imgur.com/tfDD8kl.jpg

**Comment by xcrailer** [comment]
Ok, so I fixed radarr myself. Roll back both radarr.py and ratings_radarr.py to the original versions.

The radar script is failing on grab because it is looking for the variable ratings in ratings_radarr but you failed to specifiy "ratings" as a global variable in ratings_radarr.

I just added ratings = "" and it works fine now.

**Comment by xcrailer** [comment]
Same with Sonarr, roll everything back to its original. You just have to declare ratings = "" as a global variable in ratings_radarr and declare trailer = "" as a global variable in sonarr_ratings.

This makes it work perfect.

**Comment by NiNiyas** [comment]
Great to hear that and sorry I couldn't be helpful. If you don't have any issues, please close the issue. Thanks!
